version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: peci
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edited
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
      - ./screenshots:/app/screenshots
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
